version: "3.9"

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  weaviate:
    image: semitechnologies/weaviate:1.25.2
    container_name: weaviate
    ports:
      - "8080:8080"
    environment:
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=none
      - ENABLE_MODULES=none
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: unless-stopped

  api:
    build:
      context: ./api
    container_name: rag-api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEAVIATE_URL=http://weaviate:8080
    depends_on:
      - ollama
      - weaviate

volumes:
  ollama_data:
  weaviate_data:
